### ISSUE TITLE
[Documentation] Artefacts

### ISSUE THREAD

**Issue by rubyFeedback** [RamosPabloA/NPC_Dusk_MOD#22]
Could it be explained what the new artefacts do? Any of them game breaking?

I have had installed mods in the past that were great but overpowered. For instance one of
them had some insane dragon armour that was better than every other armour. Past that
point it made no more sense to play the actual game since that item changed (and thus
downgrade) all the other items.

I don't necessarily need a listing, but perhaps some general comments of the artefacts
and a very few examples could be shown at the README.md? Thank you for potentially
considering this request.

**Comment by evancauteren** [comment]
Thanks for your feedback, buddy!
Although we aim to keep the mod as balanced as possible, I agree it would be a nice addition to have some sort of documentation in place.
After a quick internal discussion, we think that the best approach would be to first document the important stuff, just to give players some kind of context. And, in a later phase, carry on with the remaining things.

I think that repo's wiki could be a nice place to start documenting things. What are your thoughts?

**Comment by Endarire** [comment]
Adding a separate documentation page on the GitHub repo would help!

**Comment by evancauteren** [comment]
Great guys! Thanks for the feedback.
Will let you know as soon as we have some documentation in place.

**Comment by evancauteren** [comment]
Closing this ticket since we are going to track the documentation progress in https://github.com/RamosPabloA/NPC_Dusk_MOD/issues/27
