### ISSUE TITLE
Compatibility with Enhanced Edition (Trilogy)/EE(T)?

### ISSUE THREAD

**Issue by Endarire** [RamosPabloA/NPC_Dusk_MOD#23]
@evancauteren @RamosPabloA 
Greetings!  Thankee for releasing this mod!

How compatible is this with BG2EE and EET (the [Enhanced Edition Trilogy](https://github.com/Gibberlings3/EET))?

May we get EET compatibility?

Thankee!

**Comment by RamosPabloA** [comment]
Hi @Endarire! Yes, it should be compatible. There were some quests that had chapter conditionals, but those were changed to make it adaptable to EET without affecting those who have BG2 EE, nor affecting the story itself. You should not have any problems playing it in EET.
