### ISSUE TITLE
Balancing: Item Nerfing

### ISSUE THREAD

**Issue by RamosPabloA** [RamosPabloA/NPC_Dusk_MOD#28]
Nerfing list:

- Legendary swords: Mugejin/Shin-Ushi
- WS whole set
- Emerald/Crimson Sword
- Steel Warrior gem (duration nerf)

Note: The modification of the description for each item should also be made.

**Comment by evancauteren** [comment]
The following items were nerfed to better balance the game:

**SPELLS:**
- Steel Warrior (Spell)
	* Duration: 12hs -> 3hs

**WEAPONS:**
- Crimson Thunder (War Hammer)
	* Call Lightning: 5 times per day -> 3 times per day
	* Electrical damage: +2d6 -> +1d6

- Mugenjin (Legendary Sword - Evil Path)
	* Sell price: $71000 -> $1000
	* Charisma Modifier: +3 -> +2
	* Wisdom and Intelligence Modifier: +2 -> +1
	* HP Modifier: +%15 -> +%10
	* Fire Damage: +3d6 -> +2d4
	* Vorpal Strike Chance: %25 -> %15

EVIL Dusk's iconic weapon

- Crimson Sword (Bastard Sword):
	* Regeneration: 3 HP every 3 sec -> 1 HP every 6 sec
	* Fire resistance: 10% -> +5%
	* Drain: 3 HP per strike -> 1 HP per strike
	* Base Damage: 3D6 -> 2D5

- Enhanced Crimson Sword (Bastard Sword):
	* Regeneration: 3 HP every 3 sec -> 1 HP every 6 sec
	* Fire Resistance: +15% -> +10%
	* Drain: 3 HP per strike -> 1 HP per strike
	* Base Damage: 3D6 -> 2D5

- Ira (Bastard Sword):
	* Regeneration: 3 HP every 3 sec -> 1 HP every 6 sec
	* Fire Resistance: +25% -> +15%
	* Drain: 5 HP per strike -> 3 HP per strike
	* Base Damage: 3D6 -> 2D5
	* Fire Damage: 1D6 -> 1D4
	* Magical Damage: 2 -> 1D2

- Ira Tenax (Bastard Sword):
	* Regeneration: 3 HP every 3 sec -> 1 HP every 3 sec
	* Fire Resistance: +30% -> +25%
	* Base Damage: 3D6 -> 2D5
	* Fire Damage: 3D6 -> 1D8
	* Magical Damage: 3 -> 1D3

GOOD Dusk's iconic weapon

- Lux Triumphans (Bastard Sword):
	* AC: +3 -> +2
	* True Sight: 3 times per day -> 1 time per day
	* Magical Damage: 2d7 -> 2d4

**WIZARD SLAYER SET:**

- Benork's Hope (Amulet)
	* MR: +%10 -> +%5

- Aznagarb's Defense (Bracers)
	* Stone Skin: 3 times per day -> 1 time per day
	* Cure Critical Wounds: 5 times per day -> 2 times per day

- Path of the Ancestors (Boots)
	* Cold Resistance: +%25 -> +%15
	* Electricity Resistance: +%25 -> +%15

- Protection of Aznagarb (Mantle)
	* Charisma Modifier: +2 -> +1
	* Electrical Immunity: Removed

- Benork's Fortitude (Sash)
	* Constitution Modifier: +3 -> +1
	* Dexterity Modifier: +3 -> +1
	* MR: +%15 -> +%5
	* Missile Damage Resistance: +%50 -> +%25

- Iris of Tempus (Helmet)
	* Hit Points: +%10 -> +%5
	* Acid Resistance: +%25 -> +%15
	* Detect Invisibility: 3 times per day -> 1 time per day
	* True Seeing: 3 times per day -> 1 time per day

- Breath of Lineage (Ring)
	* Fire Resistance: +%10 -> +%5

- Calia's Heartbeat (Ring)
	* Fire Resistance: +%10 -> +%5

- Royal Avenger (Quarterstaff)
	* Posion damage: +2d5 -> +1d4
	* Strength: Set at 25 -> Modifier: +2

**NOTE:** All WS items price sell were diminished.

**Comment by evancauteren** [comment]
Fixed in branch 25-complete-english-translation-for-amtgen01tra
