### ISSUE TITLE
When mod is updated, incorrect names are shown on already met characters

### ISSUE THREAD

**Issue by evancauteren** [RamosPabloA/NPC_Dusk_MOD#29]
**Description:** when the mod is updated, the name of characters that were already met, are changed for another name or even for a complete dialog. This issue is **not present** if you upgrade and start a new game; it only happens when loading already started games.

**How to reproduce:** load a save state of an ongoing game and talk with a character that you already encountered previously **after** overwriting / updating the mod. 

**Workaround:** if Dusk is in the party and you press the letter K on the keyboard, the names should be fixed (it can take up to 10 seconds)

**Screenshots:**
Issue described:
![msg247581742-229242](https://user-images.githubusercontent.com/10679739/231032737-5262fcf4-4514-47e5-898a-59c557f079be.jpg)
Issue solved after pressing K:
![msg247581742-229244](https://user-images.githubusercontent.com/10679739/231032756-db19e2de-1743-4a48-a166-efcccf677706.jpg)

**Comment by evancauteren** [comment]
Closing this issue since it's probably a known issue without an easy fix.

**Comment by Endarire** [comment]
How configurable is this K key?  I like using many keyboard commands for BG.

Thankee!

**Comment by RamosPabloA** [comment]
> How configurable is this K key? I like using many keyboard commands for BG.
> 
> Thankee!

It should be easy to configure. You just need to replace the hotkey in this file. It's the first block, so it should be easy to find. Just change the 'K' for another hotkey. Obviously, you need to do this BEFORE installing the mod.
![imagen](https://user-images.githubusercontent.com/50837845/231549869-038cbaa8-22d7-42e2-b1a8-0a9dbbe64ee7.png)
