### ISSUE TITLE
[Suggestion] More ways to get the leprechaun to spawn in the main room

### ISSUE THREAD

**Issue by rubyFeedback** [RamosPabloA/NPC_Dusk_MOD#55]
Hello Ramos / evan and whoever else reads / maintains this repository,

So I was recently playing this mod again. It's one of the better mods
out there, in my opinion.

I installed lots of add-on mods and some of them cause issues. I ran
into an awkward issue where liches are in the athaklan slums.

Specifically when I enter the area where the main NPC is who will send
Dusk to tasks, where we have to find the leprechaun, some vampire
lich appears with various skeletons. I played the game on insanity
level and the damage output was too high. Once I set it back to
hard difficulty I managed to kill the lich after a long battle.

However had, I still can not find the leprechaun, which is frustrating
so I had to gt rid of Dusk since he could not get his quest started.

I am pretty certain that some of the other mods out there confuse
the Dusk quest, and the most frustrating part is how I can not
get the leprechaun to spawn; or I can not find the leprechaun. So I
have a suggestion to make here. Not all may be applicable but perhaps
you may consider:

a) After, say, 60 days of not having found the leprechaun, run a
script and check to see if the leprechaun has been spawned in the
main room. If not then perhaps let Dusk make a proposal to catch
the leprechaun by dropping some golds in the docks area, in some
box or something that already exists. Anything that can be simple
and allows us to find the leprechaun.

b) Alternatively or in addition to that, have some kind of routine
that checks for whether the leprechaun is in the main room already.
If not then perhaps Dusk can trigger some identifer routine aka
"there is the leprechaun!" and simply spawn the leprechaun nearby.

The leprechaun thing is the most frustrating part of it. I know
it works basically because I was able to get through the main
quest, which is fun, in the earlier times when I didn't install
so many mods. But some other mods are misbehaving and seem to
overwrite some areas that other mods write into or modified (e.
g. some files) and it's not always clear what to do to install
things properly. The above two suggestions are just meant to
get the leprechaun quest running. If it is not running then all
downstream quest-addons don't run, so I can not do the quests. :(

(I could use the cheat codes but I never use the cheat codes.
For some reason I prefer if things "just work" without needing
to tap into the console ever.)

(c) as another alternative would be to just hire some helpers
and pay 5000 gold coins or something like that, which can help
find the leprechaun, and after 24 hours the leprechaun has been
found.

I think the leprechaun should not be so shy to return to the
other guys - he behaves as if he hates them all. And now I can't
find him at all due to buggy other mods. :P

**Comment by rubyFeedback** [comment]
Aha - I re-read how I got those liches be so strong. It was this mod:

https://www.gibberlings3.net/mods/quests/tactics-remix/

That mod even mentions that they will re-purpose the building north of the shadow thief guildhall.

Many of these old mods are really bad. They do way too many things and cause incompatibilities
with other, better written mods such as the mod here. At the least now I know what NOT to 
install - I also suspect the tactics remix mod is one reason why I got issues with Dusk mod;
I didn't install the tactics mod before, and everything worked. Once I installed that tactics
mod I ran into issues.

**Comment by RamosPabloA** [comment]
> Hello Ramos / evan and whoever else reads / maintains this repository,
> 
> So I was recently playing this mod again. It's one of the better mods out there, in my opinion.
> 
> I installed lots of add-on mods and some of them cause issues. I ran into an awkward issue where liches are in the athaklan slums.
> 
> Specifically when I enter the area where the main NPC is who will send Dusk to tasks, where we have to find the leprechaun, some vampire lich appears with various skeletons. I played the game on insanity level and the damage output was too high. Once I set it back to hard difficulty I managed to kill the lich after a long battle.
> 
> However had, I still can not find the leprechaun, which is frustrating so I had to gt rid of Dusk since he could not get his quest started.
> 
> I am pretty certain that some of the other mods out there confuse the Dusk quest, and the most frustrating part is how I can not get the leprechaun to spawn; or I can not find the leprechaun. So I have a suggestion to make here. Not all may be applicable but perhaps you may consider:
> 
> a) After, say, 60 days of not having found the leprechaun, run a script and check to see if the leprechaun has been spawned in the main room. If not then perhaps let Dusk make a proposal to catch the leprechaun by dropping some golds in the docks area, in some box or something that already exists. Anything that can be simple and allows us to find the leprechaun.
> 
> b) Alternatively or in addition to that, have some kind of routine that checks for whether the leprechaun is in the main room already. If not then perhaps Dusk can trigger some identifer routine aka "there is the leprechaun!" and simply spawn the leprechaun nearby.
> 
> The leprechaun thing is the most frustrating part of it. I know it works basically because I was able to get through the main quest, which is fun, in the earlier times when I didn't install so many mods. But some other mods are misbehaving and seem to overwrite some areas that other mods write into or modified (e. g. some files) and it's not always clear what to do to install things properly. The above two suggestions are just meant to get the leprechaun quest running. If it is not running then all downstream quest-addons don't run, so I can not do the quests. :(
> 
> (I could use the cheat codes but I never use the cheat codes. For some reason I prefer if things "just work" without needing to tap into the console ever.)
> 
> (c) as another alternative would be to just hire some helpers and pay 5000 gold coins or something like that, which can help find the leprechaun, and after 24 hours the leprechaun has been found.
> 
> I think the leprechaun should not be so shy to return to the other guys - he behaves as if he hates them all. And now I can't find him at all due to buggy other mods. :P

Thanks for the very interesting suggestions for the leprechaun's quest. We've already implemented some bug fixes for this quest in the upcoming v1.1. We hope this will solve some issues regarding incompatibility with other mods.

**Comment by RamosPabloA** [comment]
> Aha - I re-read how I got those liches be so strong. It was this mod:
> 
> https://www.gibberlings3.net/mods/quests/tactics-remix/
> 
> That mod even mentions that they will re-purpose the building north of the shadow thief guildhall.
> 
> Many of these old mods are really bad. They do way too many things and cause incompatibilities with other, better written mods such as the mod here. At the least now I know what NOT to install - I also suspect the tactics remix mod is one reason why I got issues with Dusk mod; I didn't install the tactics mod before, and everything worked. Once I installed that tactics mod I ran into issues.

This is very interesting. I'll try that mod and see if I can replicate the bug you mentioned. Once I do, I'll try to apply a patch to it.

Thank you.
