### ISSUE TITLE
[FAQ entry proposal] Good versus Evil for Dusk

### ISSUE THREAD

**Issue by rubyFeedback** [RamosPabloA/NPC_Dusk_MOD#56]
The README mentions "A path to convert Dusk into a Good or Evil alignment".

So far I only chose the Good alignment path.

Would it be possible for the FAQ to briefly mention the main differences
here, aside of the alignment? Will items be different?

So far I only played the Good path but I am thinking of trying the Evil path next
for a full evil party anyway. I also noticed Dusk fighting against Dorn - would be
interesting if the evil path chosen allows Dusk to go together with Dorn. (I actually
dislike Dorn but his abilities are kind of interesting.)

**Comment by RamosPabloA** [comment]
Yes, we will add this to the README file. In the meantime, I'll share some details regarding this feature:
![10](https://github.com/RamosPabloA/NPC_Dusk_MOD/assets/50837845/ea1f6b50-3259-4196-a08a-8a9907bb437d)
![21](https://github.com/RamosPabloA/NPC_Dusk_MOD/assets/50837845/a0be45b1-c7f2-4c82-9648-b8cb05ea8fbb)
