### ISSUE TITLE
[Bug, but possibly not related to this mod - so just info] All is spawned twice

### ISSUE THREAD

**Issue by rubyFeedback** [RamosPabloA/NPC_Dusk_MOD#60]
Just some information, please feel free to proceed in any way as you see fit.

I installed some mods, and at place #14 Dusk mod. But I had some problems,
some mod was overwriting things again. I then re-installed the Dusk mod and
things were mostly fine. But now all spawnable things are spawned twice.
So at the fight in the troll mound, I now have twice the number of opponents. :)

I am not sure this is related at all to the mod here; but perhaps there can be
additional checks to ensure things are only ever spawned once.

**Comment by RamosPabloA** [comment]
If you see duplicate things, you can fix it by deleting the mod files in the override folder and reinstalling the mod.

To prevent this from happening, you should uninstall the mod before reinstalling it. I'm not sure why this happens, but it's a good idea to be safe.

The check to prevent duplicates is a good idea. I'll try to implement it in my next release.
