### ISSUE TITLE
[Rebalancing thoughts] Vorpal effects

### ISSUE THREAD

**Issue by rubyFeedback** [RamosPabloA/NPC_Dusk_MOD#78]
In my current run-through, the two main fighters in my party of six are Dusk and
Korgan. Both are very powerful. I think Korgan is actually a little bit stronger, due
to items (hammer giving 25 str and the vorpal axe now); though Dusk can do 
oath of fury, so both are strong.

However had, the vorpal effect is making winning fights quite easy.

For instance, in the final fight for Dusk, where we face four enemy mages and
some helper allies, Korgan rushes in under berzerk. I actually waited for this
and amassed even more XP so he can whirlwind. He single-handedly killed
three of the enemy mages due to vorpal effect.

Lateron I did Tower of Deception. Admittedly when you are at a high level,
many mods are quite easy, but Korgan slew Ustain (the final boss) via
a vorpal strike. I had similar results lateron.

I believe the vorpal effect in and by itself is not necessarily overpowered.
But I think the scaling effect has to be considered, as well as the percentage;
I think it is 10% or so, and if one whirlwinds while under haste, this is 
pretty deadly.

I am not suggesting to re-balance the mod, even though (while it is my
favourite mod) it is a powerful mod overall, and I am not really wanting
to suggest to nerf it, I believe some of the "high end's" effects should be
considered - vorpal effect of the axe in particular.

I am not sure how to rebalance it, should this be done, but I think the
10% chance is too high. I thought about, say, decreasing it to 5% or 
something like that. Or even below that. What if it only happens on a
critical hit? I think that is a 5% chance, a roll of 20 on a D20 (though I
think in some gamebook rules of ADnD, 19 may also count as a 
critical hit, so this rebalancing would not have a real change if both
19 and 20 count as critical).

The save versus the vorpal effect could also be made a bit easier.

IF vorpal effect is nerfed then perhaps the axe could get some other
bonus, perhaps increasing the luck of Korgan for a bit. Or a new 
ability such as some extra damage such as +1 acid or anything
like that. 

A more serious change would be to remove vorpal effect and replace
it with some other good effect. Perhaps the 10% chance could be
kept but it would do additional damage. Could be slash or piece
damage perhaps... hmm slash may make more sense for an axe.
Some mod add-on has a spear or so that adds +10 damage base
flat on a hit. Anyway - the idea is to slightly reduce the power, at
the least on a high end char.

Another idea could be to keep vorpal effect but to cause a cooldown
after it has triggered once, say 2 rounds or so where vorpal 
does not is in effect AFTER it was triggered. That would just be
a small nerf and probably not change that much, except that
chain-vorpaling enemy units with Korgan rushing through solo
would be a bit less likely than it is right now.

Getting rewards is great but I think some effects are overpowered.
(Flail of Ages slow effect in vanilla games of BG2 is also overpowered,
IMO, but I guess it is a tiny bit below vorpal insta-kill effects.)

Anyway, it's just an idea - don't worry too much about it either way
and feel free to close the issue down at any moment in time for
any reason.

**Comment by RamosPabloA** [comment]
Greetings! The nerf to the Golden Axe was planned. Its chance will be lowered to 3%, and the save vs. death penalty will change from -4 to -2. To compensate for this, 1 point of magical damage per hit will be added.

However, the Dusk mod will now transition to a larger mod called Autumn's Twilight. It will include more quests, more joinable NPCs, new magic spells, some new kits, new animations for new enemies, and new areas. All content from Dusk will be integrated into this new mod, and maintenance will take place there. Therefore, the next update for Dusk will be in this new mod, in a new repository. I will post here and in various sites when I have the new repository, which will be very soon.
