### ISSUE TITLE
[Request] Main Page README: Show the entire license text at or near the bottom.

### ISSUE THREAD

**Issue by Endarire** [RamosPabloA/NPC_Dusk_MOD#81]
Greetings, all!

Since Dusk has an explicit license, I request the text of this license be reproduced at or near the bottom of the GitHub main page README so people can easily read it if they want.

Thankee, @RamosPabloA!

**Comment by evancauteren** [comment]
Hello there!
I've added the license text in the readme.md. Thanks for pointing this out!
