### ISSUE TITLE
Crossmod Permission Clarification

### ISSUE THREAD

**Issue by Endarire** [RamosPabloA/NPC_Dusk_MOD#84]
Greetings, all!

Do others have permission to do crossmod with Dusk?  I assumed so.  Regardless, I request you mention your crossmod stance clearly on the main page's README.

Thankee!

**Comment by Endarire** [comment]
@RamosPabloA 
Checking in.

Thankee!

**Comment by evancauteren** [comment]
Hello there, Endarire.
I've taken care of your request!

Eduardo.
